services:
  db:
    image: postgres:16
    container_name: odoo18_database
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: Pankaj@123
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    container_name: odoo18
    ports:
      - 8044:8069
    stdin_open: true
    tty: true
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: Pankaj@123
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    command:
      ["odoo", "-c", "/etc/odoo/odoo.conf"]
    volumes:
      - odoo:/var/lib/odoo
      - ./custom_addons:/mnt/extra-addons
      - ./odoo.conf:/etc/odoo/odoo.conf
    restart: unless-stopped
volumes:
  postgres:
  odoo:
